const ADD_CART = "ADD_CART";
const REMOVE_CART = "REMOVE_CART";
const UPDATE_CART = "UPDATE_CART";
const DEFAULT = "DEFAULT";
const INCREASE = "INCREASE";
const REDUCED = "REDUCED";
const FINDIDX = "FINDIDX";
const CHANGEVL = "CHANGEVL";
const SUBMIT = "SUBMIT";

export {
  ADD_CART,
  REMOVE_CART,
  UPDATE_CART,
  DEFAULT,
  INCREASE,
  REDUCED,
  FINDIDX,
  CHANGEVL,
  SUBMIT
};
