const ADD_CART = "ADD_CART";
const REMOVE_CART = "REMOVE_CART";
const UPDATE_CART = "UPDATE_CART";
const DEFAULT = "DEFAULT";
const INCREASE = "INCREASE";
const REDUCED = "REDUCED";

export { ADD_CART, REMOVE_CART, UPDATE_CART, DEFAULT, INCREASE, REDUCED };
